// ==UserScript==
// @name         Cookie Clicker Advanced Panel 
// @namespace    https://github.com/you
// @version      3.0.8
// @description  左下の⚙で開くパネル。毎秒のコスパ計算、フィルター、自動購入、自動クリック、自動ゴールデンクッキークリック、自動トナカイクリック、一括売却/購入、手動購入に加え、同時発生検出・MP回復目安・セーブ入出力を追加。設定はローカルに保存されます。
// @author       Generated by ChatGPT, Modified by User Request
// @match        https://orteil.dashnet.org/cookieclicker/*
// @match        http://orteil.dashnet.org/cookieclicker/*
// @grant        none
// ==/UserScript==

(function() {
    'use strict';
    // --- 設定キー ---
    const LS_KEY = 'cc_advanced_panel_v1'; // v1キーを流用して設定を引き継ぐ

// --- 建物日本語名 ---
const BUILDING_META = [
    { id: 0, name: 'カーソル' },
    { id: 1, name: 'グランマ' },
    { id: 2, name: '農場' },
    { id: 3, name: '鉱山' },
    { id: 4, name: '工場' },
    { id: 5, name: '銀行' },
    { id: 6, name: '神殿' },
    { id: 7, name: '魔法使いの塔' },
    { id: 8, name: '宇宙船' },
    { id: 9, name: '錬金術室' },
    { id: 10, name: 'ポータル' },
    { id: 11, name: 'タイムマシン' },
    { id: 12, name: '反物質凝縮器' },
    { id: 13, name: 'プリズム' },
    { id: 14, name: 'チャンスメーカー' },
    { id: 15, name: '自己無限生成エンジン' },
    { id: 16, name: 'Javascriptコンソール' },
    { id: 17, name: '遊休宇宙' },
    { id: 18, name: 'コーテックス・ベイカー' },
    { id: 19, name: 'あなた' }
];

// --- ヘルパー: ローカルストレージ読み書き ---
function loadSettings() {
    try { const s = localStorage.getItem(LS_KEY); return s ? JSON.parse(s) : null; } catch (e) { return null; }
}
function saveSettings(obj) { try { localStorage.setItem(LS_KEY, JSON.stringify(obj)); } catch (e) { console.error('saveSettings', e); } }

// --- 初期設定 ---
const defaults = {
    n: 5,
    excluded: {}, // id:true means excluded
    autoPurchase: false,
    autoClick: false,
    autoGolden: false,
    autoReindeer: false, // ★新機能★
    bulkTradeState: 'sell', // 'sell' または 'buy'
    soldSnapshot: {}, // 売却時のスナップショット
    panelOpen: false
};
const loaded = loadSettings() || {};
const state = Object.assign({}, defaults, loaded);

// --- 内部ランタイム状態（追加機能用・非保存） ---
const runtime = {
    // 1) Frenzy(7x)+施設ブースト 同時発生検出用
    duoActive: false, // 現在同時発生中か（フラグ）
    savedOnDetect: null, // 検出時点のセーブデータ（最新）
    copyVisible: false, // 左上「検出しました！ コピー」表示フラグ
    // 2) MP回復目安表示用キャッシュ
    lastMpText: '残り--分',
};


// --- UI 要素 ---
const CSS = `
 #ccadv_root{font-family:Arial,Helvetica,sans-serif}
 #ccadv_btn{position:fixed;left:12px;bottom:12px;z-index:2147483646;background:#222;color:#fff;border-radius:6px;padding:8px 10px;cursor:pointer;box-shadow:0 4px 10px rgba(0,0,0,0.5)}
 #ccadv_panel{position:fixed;left:12px;bottom:56px;z-index:2147483646;background:rgba(10,10,10,0.95);color:#fff;padding:12px;border-radius:8px;box-shadow:0 6px 18px rgba(0,0,0,0.6);width:360px;max-width:calc(100vw - 24px)}
 #ccadv_panel .row{display:flex;align-items:center;justify-content:space-between}
 #ccadv_panel .small{font-size:12px;opacity:0.9}
 #ccadv_building_list{max-height:240px;overflow:auto;margin-top:8px;background:rgba(255,255,255,0.03);padding:6px;border-radius:6px}
 .ccadv_building_item{display:flex;align-items:center;gap:8px;padding:6px;border-radius:6px}
 .ccadv_toplist{margin-top:8px}
 .ccadv_control{display:flex;gap:8px;align-items:center}
 .ccadv_btnsmall{background:transparent;border:1px solid rgba(255,255,255,0.12);padding:4px 8px;border-radius:6px;color:#fff;cursor:pointer}
 .ccadv_backbtn{background:transparent;border:1px solid rgba(255,255,255,0.12);padding:6px 8px;border-radius:6px;color:#fff;cursor:pointer;margin-right:8px}
 .ccadv_btnsmall:disabled{opacity:0.5;cursor:not-allowed}

 /* ▼▼▼ 追加機能CSS ▼▼▼ */
 #ccadv_feature_bar{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-top:6px; margin-bottom: 8px;}
 #ccadv_topbar_left{min-height:22px;display:flex;align-items:center;gap:6px; font-size: 11px;}
 #ccadv_topbar_center{min-height:22px;flex:1;text-align:center; font-size: 11px; font-weight: bold;}
 #ccadv_topbar_right{min-height:22px;display:flex;gap:6px;align-items:center;justify-content:flex-end}
 /* ▲▲▲ 追加機能CSS ▲▲▲ */
`;

// inject CSS
let style = document.getElementById('ccadv_style');
if (style) style.remove();
style = document.createElement('style');
style.id = 'ccadv_style';
style.textContent = CSS;
document.head.appendChild(style);

// root container (only once)
let root = document.getElementById('ccadv_root');
if (!root) { root = document.createElement('div');
    root.id = 'ccadv_root';
    document.body.appendChild(root); }

// settings button ⚙ (only once)
let gear = document.getElementById('ccadv_btn');
if (!gear) {
    gear = document.createElement('button');
    gear.id = 'ccadv_btn';
    gear.title = 'Open CC Advanced Panel';
    gear.innerHTML = '⚙';
    root.appendChild(gear);
    gear.addEventListener('click', () => { renderMainView(); panel.style.display = 'block'; state.panelOpen = true; saveSettings(state); });
}

// panel (create if needed)
let panel = document.getElementById('ccadv_panel');
if (!panel) {
    panel = document.createElement('div');
    panel.id = 'ccadv_panel';
    panel.style.display = state.panelOpen ? 'block' : 'none';
    document.body.appendChild(panel);
}

// ▼▼▼ --- 追加機能ヘルパー --- ▼▼▼

// クリップボード書き込みヘルパー
async function writeToClipboard(text) {
    try {
        if (navigator.clipboard && window.isSecureContext) {
            await navigator.clipboard.writeText(text);
            return true;
        } else {
            // http: or fallback
            const ta = document.createElement('textarea');
            ta.value = text;
            ta.style.position = 'fixed';
            ta.style.opacity = '0';
            document.body.appendChild(ta);
            ta.focus();
            ta.select();
            const ok = document.execCommand('copy');
            document.body.removeChild(ta);
            return ok;
        }
    } catch (e) {
        console.error('Clipboard write failed', e);
        return false;
    }
}

// --- Frenzy7x + 建物ブースト検出（Refactoring対応・完成版） ---
function hasFrenzy7x() {
    try {
        if (!window.Game || !Game.buffs) return false;
        for (const [id, buff] of Object.entries(Game.buffs)) {
            if (!buff || !buff.name) continue;
            if (buff.multCpS && Math.abs(buff.multCpS - 7) < 0.2) return true;
            if (/frenzy/i.test(buff.name) && buff.multCpS && buff.multCpS > 6) return true;
        }
    } catch (e) { console.warn("[DEBUG] hasFrenzy7x error", e); }
    return false;
}

function hasBuildingBoost() {
    try {
        if (!window.Game || !Game.buffs) return false;

        // 現行版の建物ブースト名を追加
        const buildingBoostNames = [
            "High-five", "Conglomerate", "Luxurious", "Great loop",
            "Building special", "Elder frenzy (building boost)",
            "Refactoring" // ← これを追加！
        ];

        for (const [id, buff] of Object.entries(Game.buffs)) {
            if (!buff || !buff.name) continue;
            if (buildingBoostNames.some(n => buff.name.includes(n))) {
                console.log("[DEBUG] Building boost via name:", buff.name, buff);
                return true;
            }
            if (buff.buildingTie && buff.multCpS && buff.multCpS > 1) {
                console.log("[DEBUG] Building boost via buildingTie:", buff);
                return true;
            }
        }
    } catch (e) { console.warn("[DEBUG] hasBuildingBoost error", e); }
    return false;
}

function checkFrenzyBuildingCombo() {
    if (!window.Game || !Game.ready || !Game.buffs) return;

    const frenzy = hasFrenzy7x();
    const building = hasBuildingBoost();

    if (frenzy && building) {
        // 同時発生中
        if (!runtime.duoActive) {
            // 🟢 初回検出：ここでセーブを固定保存
            runtime.duoActive = true;
            runtime.savedOnDetect = Game.WriteSave(1);
            runtime.copyVisible = true;
            updateDetectUI();
            console.log("★★ Frenzy7x + Building Boost 同時発生 detected! (セーブ固定) ★★");
        } else {
            // 🔵 すでに検出済み → 何もしない（セーブを上書きしない）
        }

    } else {
        // 🟠 同時発生が終了したらフラグをリセット（UIは維持）
        if (runtime.duoActive) {
            runtime.duoActive = false;
            console.log("[DEBUG] Frenzy+Boost 終了 - 状態リセット（UI保持）");
        }
    }
}




(function waitForGame() {
    const timer = setInterval(() => {
        if (window.Game && Game.ready) {
            clearInterval(timer);
            console.log("[DEBUG] ✅ Game loaded - monitoring buffs (Refactoring対応版)");
            setInterval(checkFrenzyBuildingCombo, 2000);
        }
    }, 1000);
})();

// 2. MP回復目安（FtHoF + Diminish Ineptitude 合計までの分数）
function computeMinutesToSumCost() {
    try {
        if (!window.Game || !Game.ObjectsById || !Game.ObjectsById[7] || !Game.ObjectsById[7].minigame) return null;

        const wiz = Game.ObjectsById[7];
        const n = wiz.amount || 0;
        const Lv = wiz.level || 1;

        // 最大MP = floor(4 + n^0.6 + 15ln(1 + n/15 + (2/3)(Lv-1)))
        const maxMP = Math.floor(4 + Math.pow(n, 0.6) + 15 * Math.log(1 + n/15 + (2/3)*(Lv-1)));

        const minigame = wiz.minigame;
        const curMP = (minigame && typeof minigame.magic === 'number') ? minigame.magic : 0;

        // 消費MP
        const costFtHoF = 10 + 0.6 * maxMP;
        const costDiminish = 5 + 0.2 * maxMP;
        const targetSum = costFtHoF + costDiminish; // = 15 + 0.8*maxMP

        // 目標は理論上 targetSum だが、MPは最大値を超えないため、実際到達可能な上限は maxMP
        const target = Math.min(targetSum, maxMP);

        if (curMP >= target) return 0; // 既に足りている

        // 回復量/フレーム = max(0.000004, (現在MP / max(100, 最大MP))^0.5 * 0.002)
        const M2 = Math.max(100, maxMP);
        const fps = Game.fps || 30;
        const rmin = 0.000004; // 最小回復量
        const c = 0.002 / Math.sqrt(M2); // 回復係数: dp/dt = c*sqrt(p)

        const p0 = curMP; // 開始MP
        const pT = target; // 目標MP

        // 回復レートが rmin から c*sqrt(p) に切り替わる閾値 p*
        // rmin = c * sqrt(pStar) => pStar = (rmin / c)^2
        const pStar = Math.pow(rmin / c, 2);

        let frames = 0;

        if (pT <= pStar) {
            // 目標MPが閾値以下なら、ずっと最小回復
            frames = (pT - p0) / rmin;
        } else {
            if (p0 < pStar) {
                // 閾値未満からスタート
                // 1. p0 -> pStar (最小回復)
                frames += (pStar - p0) / rmin;
                // 2. pStar -> pT (変動回復)
                // dt = dp / (c*sqrt(p)) の積分 -> t = (2/c) * (sqrt(pT) - sqrt(pStar))
                frames += (2 / c) * (Math.sqrt(pT) - Math.sqrt(pStar));
            } else {
                // 閾値以上からスタート
                // 1. p0 -> pT (変動回復)
                frames += (2 / c) * (Math.sqrt(pT) - Math.sqrt(p0));
            }
        }

        if (!isFinite(frames) || frames < 0) return null;

        const minutes = (frames / fps) / 60;
        return Math.max(0, minutes);

    } catch(e){
        // 計算失敗
        return null;
    }
}

function formatMinutes(mins) {
    if (mins == null) return '残り--分';
    if (mins <= 0) return '残り0分';
    // 小数点以下1桁で表示
    return '残り' + mins.toFixed(1) + '分';
}

// 3. UI更新用関数
function updateDetectUI() {
    const leftEl = document.getElementById('ccadv_topbar_left');
    if (!leftEl) return;

    if (runtime.copyVisible && runtime.savedOnDetect) {
        // 表示フラグが立っており、中身がボタンでなければ（二重描画防止）
        if (!leftEl.querySelector('#ccadv_detect_copy')) {
            leftEl.innerHTML = ''; // 既存の表示をクリア
            const msg = document.createElement('span');
            msg.textContent = '検出しました！';
            const btn = document.createElement('button');
            btn.id = 'ccadv_detect_copy';
            btn.className = 'ccadv_btnsmall';
            btn.textContent = 'コピー';
            btn.title = '検出時点のセーブデータをコピー';

            btn.addEventListener('click', async () => {
                try {
                    if (runtime.savedOnDetect) {
                        const ok = await writeToClipboard(runtime.savedOnDetect);
                        if (ok) {
                            // コピー成功したら非表示にする
                            runtime.copyVisible = false;
                            updateDetectUI();
                        } else {
                            alert('クリップボードへのコピーに失敗しました。');
                        }
                    }
                } catch(e) {
                    alert('コピーに失敗しました。');
                }
            });
            leftEl.appendChild(msg);
            leftEl.appendChild(btn);
        }
    } else {
        // 表示フラグが false なら非表示
        leftEl.innerHTML = '';
    }
}

function updateMpUI() {
    const centerEl = document.getElementById('ccadv_topbar_center');
    if (!centerEl) return;

    const mins = computeMinutesToSumCost();
    const txt = formatMinutes(mins);

    // 表示テキストが変化した場合のみDOMを更新
    if (txt !== runtime.lastMpText) {
        runtime.lastMpText = txt;
        centerEl.textContent = txt;
    }
}

async function handleExportSave() {
    try {
        if (!window.Game || typeof Game.WriteSave !== 'function') return;
        let s = '';
        try {
            s = Game.WriteSave(1); // 1 = 生データ
        } catch(e) {
            s = localStorage.getItem('CookieClickerGame') || '';
        }

        const ok = await writeToClipboard(s);
        if (!ok) alert('セーブデータのコピーに失敗しました。');

    } catch(e) {
        alert('セーブデータのコピーに失敗しました。');
    }
}

// ▼▼▼ 修正点 1: インポートボタンの動作を変更 ▼▼▼
function handleImportSave() { // async を削除
    try {
        // ユーザーの要望に基づき、Ctrl+O と同じゲーム標準のインポートダイアログを開く
        if (window.Game && typeof Game.ImportSave === 'function') {
            Game.ImportSave();
        } else {
            alert('インポート機能が利用できません。');
        }
    } catch(e) {
        alert('インポートの実行に失敗しました。');
    }
}
// ▲▲▲ 修正点 1 ▲▲▲

// ▲▲▲ --- 追加機能ヘルパー --- ▲▲▲


// We'll use view modes inside panel: 'main', 'filter', 'manualbuy'
function renderMainView() {
    panel.innerHTML = `
  <div style="display:flex;justify-content:space-between;align-items:flex-start;">
    <div style="font-weight:700;">CC アドバンストパネル</div>
    <div style="display:flex;gap:6px;align-items:center;flex-wrap:wrap;justify-content:flex-end;max-width:260px;">
      <label style="display:flex;align-items:center;gap:4px;font-size:11px;"><input type="checkbox" id="ccadv_autoPurchase"> 自動購入</label>
      <button id="ccadv_bulkTradeBtn" class="ccadv_btnsmall" style="padding: 3px 6px; font-size: 11px;">一括売却</button>
      <button id="ccadv_manual_buy" class="ccadv_btnsmall" style="padding: 3px 6px; font-size: 11px;">手動購入</button>
      <button id="ccadv_filter_toggle" class="ccadv_btnsmall" style="padding: 3px 6px; font-size: 11px;">ﾌｨﾙﾀｰ</button>
      <button id="ccadv_close" class="ccadv_btnsmall" style="padding: 3px 6px; font-size: 11px;">✕</button>
    </div>
  </div>

  <div id="ccadv_feature_bar">
    <div id="ccadv_topbar_left">
      </div>
    <div id="ccadv_topbar_center">
      ${runtime.lastMpText}
    </div>
    <div id="ccadv_topbar_right">
      <button id="ccadv_export_btn" class="ccadv_btnsmall" title="セーブデータをクリップボードにエクスポート" style="padding: 3px 6px; font-size: 11px;">↑</button>
      <button id="ccadv_import_btn" class="ccadv_btnsmall" title="ゲームのインポートダイアログを開く" style="padding: 3px 6px; font-size: 11px;">↓</button>
    </div>
  </div>
  <div style="margin-top:8px;display:flex;align-items:center;gap:8px;">
    表示数: <button id="ccadv_minus" class="ccadv_btnsmall">−</button>
    <div id="ccadv_n" style="min-width:24px;text-align:center">${state.n}</div>
    <button id="ccadv_plus" class="ccadv_btnsmall">＋</button>
    <div style="flex:1"></div>
    <label style="display:flex;align-items:center;gap:4px;font-size:11px;"><input type="checkbox" id="ccadv_autoClick"> 自動ｸﾘｯｸ</label>
    <label style="display:flex;align-items:center;gap:4px;font-size:11px;"><input type="checkbox" id="ccadv_autoGolden"> 自動金ｸｯｷｰ</label>
    <label style="display:flex;align-items:center;gap:4px;font-size:11px;"><input type="checkbox" id="ccadv_autoReindeer"> 自動ﾄﾅｶｲ</label>
    </div>
  <div id="ccadv_toplist" class="ccadv_toplist"></div>
  <div id="ccadv_building_list" class="ccadv_building_list" style="display:none"></div>
  <div class="small" style="margin-top:8px;opacity:0.95">※ 表示対象は現在所持している建物のみ。フィルター済みの建物は表示/自動購入の対象外になります。</div>
 `;

    // wire elements
    const el = {
        close: document.getElementById('ccadv_close'),
        nDisplay: document.getElementById('ccadv_n'),
        plus: document.getElementById('ccadv_plus'),
        minus: document.getElementById('ccadv_minus'),
        filterToggle: document.getElementById('ccadv_filter_toggle'),
        toplist: document.getElementById('ccadv_toplist'),
        buildingList: document.getElementById('ccadv_building_list'),
        autoPurchase: document.getElementById('ccadv_autoPurchase'),
        autoClick: document.getElementById('ccadv_autoClick'),
        autoGolden: document.getElementById('ccadv_autoGolden'),
        autoReindeer: document.getElementById('ccadv_autoReindeer'), // ★新機能★
        bulkTradeBtn: document.getElementById('ccadv_bulkTradeBtn'),
        manualBuy: document.getElementById('ccadv_manual_buy'),
        // ▼▼▼ NEW ▼▼▼
        exportBtn: document.getElementById('ccadv_export_btn'),
        importBtn: document.getElementById('ccadv_import_btn')
        // ▲▲▲ NEW ▲▲▲
    };

    // initialize control values from state
    el.nDisplay.textContent = state.n;
    el.autoPurchase.checked = !!state.autoPurchase;
    el.autoClick.checked = !!state.autoClick;
    el.autoGolden.checked = !!state.autoGolden;
    el.autoReindeer.checked = !!state.autoReindeer; // ★新機能★
    el.bulkTradeBtn.textContent = (state.bulkTradeState === 'buy') ? '一括購入' : '一括売却';

    // ▼▼▼ NEW ▼▼▼
    // 追加: 検出UIとMP表示初期更新
    updateDetectUI();
    updateMpUI();

    // 追加: セーブ入出力イベント
    el.exportBtn.addEventListener('click', handleExportSave);
    el.importBtn.addEventListener('click', handleImportSave); // 修正された handleImportSave を呼ぶ
    // ▲▲▲ NEW ▲▲▲


    el.close.addEventListener('click', () => { panel.style.display = 'none';
        state.panelOpen = false;
        saveSettings(state); });
    gear.addEventListener('click', () => { panel.style.display = 'block';
        state.panelOpen = true;
        saveSettings(state); });
    el.plus.addEventListener('click', () => { if (state.n < 20) { state.n++;
            el.nDisplay.textContent = state.n;
            saveSettings(state); } });
    el.minus.addEventListener('click', () => { if (state.n > 1) { state.n--;
            el.nDisplay.textContent = state.n;
            saveSettings(state); } });

    el.autoPurchase.addEventListener('change', () => { state.autoPurchase = el.autoPurchase.checked;
        saveSettings(state); });
    el.autoClick.addEventListener('change', () => { state.autoClick = el.autoClick.checked;
        saveSettings(state);
        performAutoClick(state.autoClick); });
    el.autoGolden.addEventListener('change', () => { state.autoGolden = el.autoGolden.checked;
        saveSettings(state);
        performAutoGolden(state.autoGolden); });

    // ▼▼▼ ★新機能★ ▼▼▼
    el.autoReindeer.addEventListener('change', () => { state.autoReindeer = el.autoReindeer.checked;
        saveSettings(state);
        performAutoReindeer(state.autoReindeer); });
    // ▲▲▲ ★新機能★ ▲▲▲

    el.bulkTradeBtn.addEventListener('click', () => {
        if (state.bulkTradeState === 'sell') {
            // --- 売却ロジック ---
            state.soldSnapshot = {}; // スナップショットをリセット
            // 除外対象: Cursor(0), Temple(6), Wizard Tower(7), You(19)
            const excludeIds = new Set([0, 6, 7, 19]);

            Game.ObjectsById.forEach(obj => {
                if (!obj) return;
                if (excludeIds.has(obj.id)) return; // 除外対象はスキップ

                const amt = obj.amount;
                if (amt > 0) {
                    state.soldSnapshot[obj.id] = amt; // 売却量をスナップショットに保存
                    obj.sell(amt); // 現在の全量を売却
                }
            });

            // 状態とボタンテキストを「購入」モードに切り替え
            state.bulkTradeState = 'buy';
            el.bulkTradeBtn.textContent = '一括購入';

        } else {
            // --- 購入ロジック ---
            for (const id in state.soldSnapshot) {
                const obj = Game.ObjectsById[id];
                const targetAmount = state.soldSnapshot[id] || 0;
                if (!obj || targetAmount === 0) continue;

                const currentAmount = obj.amount;
                // 不足分だけ購入
                const needToBuy = Math.max(0, targetAmount - currentAmount);

                if (needToBuy > 0) {
                    obj.buy(needToBuy);
                }
            }

            // 購入が完了したらスナップショットをリセット
            state.soldSnapshot = {};

            // 状態とボタンテキストを「売却」モードに切り替え
            state.bulkTradeState = 'sell';
            el.bulkTradeBtn.textContent = '一括売却';
        }

        // ボタンの状態とスナップショット（空の場合も）を保存
        saveSettings(state);
    });

    el.manualBuy.addEventListener('click', () => { renderManualBuyView(); });
    el.filterToggle.addEventListener('click', () => { renderFilterView(); });

    // toggle quick building list display
    el.toplist.addEventListener('dblclick', () => {
        el.buildingList.style.display = el.buildingList.style.display === 'block' ? 'none' : 'block';
    });

    // initial render content
    computeAndRenderInto(el.toplist, el.buildingList);
}

function renderFilterView() {
    panel.innerHTML = `
  <div style="display:flex;justify-content:space-between;align-items:center;">
    <div style="font-weight:700;">フィルター設定</div>
    <div>
      <button id="ccadv_filter_back" class="ccadv_backbtn">戻る</button>
      <button id="ccadv_filter_save" class="ccadv_btnsmall">保存</button>
    </div>
  </div>
  <div id="ccadv_filter_list" style="max-height:300px;overflow:auto;margin-top:8px;padding:6px;background:rgba(255,255,255,0.03);border-radius:6px"></div>
 `;

    const listEl = document.getElementById('ccadv_filter_list');

    // render all buildings with checkbox
    BUILDING_META.forEach(b => {
        const row = document.createElement('div');
        row.style.display = 'flex';
        row.style.alignItems = 'center';
        row.style.gap = '8px';
        row.style.marginBottom = '6px';
        const cb = document.createElement('input');
        cb.type = 'checkbox';
        cb.checked = !!state.excluded[b.id];
        const lbl = document.createElement('div');
        lbl.textContent = b.name + ' (id:' + b.id + ')';
        lbl.style.flex = '1';
        row.appendChild(cb);
        row.appendChild(lbl);
        listEl.appendChild(row);
        cb.addEventListener('change', () => { state.excluded[b.id] = cb.checked; });
    });

    document.getElementById('ccadv_filter_back').addEventListener('click', () => { renderMainView(); });
    document.getElementById('ccadv_filter_save').addEventListener('click', () => { saveSettings(state);
        renderMainView(); });
}

// --- 手動購入ビュー ---
function renderManualBuyView() {
    panel.innerHTML = `
      <div style="display:flex;justify-content:space-between;align-items:center;">
        <div style="font-weight:700;">手動購入</div>
        <div>
          <button id="ccadv_manual_back" class="ccadv_backbtn">戻る</button>
        </div>
      </div>
      <div style="display:grid; grid-template-columns: minmax(80px, 1fr) 135px 45px auto; align-items:center; font-size:10px; padding: 4px 0; border-bottom: 1px solid #444; gap: 4px;">
        <div style="grid-column: 1;">施設名</div>
        <div style="grid-column: 2; text-align:center;">購入数</div>
        <div style="grid-column: 3; text-align:center;">購入後</div>
        <div style="grid-column: 4; text-align:right;">必要クッキー</div>
      </div>
      <div id="ccadv_manual_list" style="max-height:280px; overflow-y:auto; overflow-x:hidden; margin-top:8px; padding:0 4px; background:rgba(255,255,255,0.03); border-radius:6px">
        </div>
      <div style="margin-top:8px; display:flex; justify-content:space-between; align-items:center;">
        <button id="ccadv_manual_buy_all" class="ccadv_btnsmall" style="padding: 6px 12px;">一括購入</button>
        <div style="text-align:right; font-size:12px;">
          合計: <span id="ccadv_manual_total_cost" style="font-weight:700; font-size: 14px;">0</span>
        </div>
      </div>
    `;

    const listEl = document.getElementById('ccadv_manual_list');
    const totalCostEl = document.getElementById('ccadv_manual_total_cost');
    const buyAllBtn = document.getElementById('ccadv_manual_buy_all');

    const buildingUIs = [];

    // コスト計算とUI更新
    function updateAllCosts() {
        let totalCost = 0;
        buildingUIs.forEach(ui => {
            const k = parseInt(ui.kInput.value) || 0;
            const obj = ui.obj;
            let cost = 0;
            const k_clamped = Math.max(0, k);
            if (k_clamped > 0) {
                // C(n, k) = Cn+1 * (1.15^k - 1) / 0.15
                cost = obj.price * (Math.pow(1.15, k_clamped) - 1) / 0.15;
            }
            ui.costEl.textContent = beautify(cost);
            if (ui.checkbox.checked) {
                totalCost += cost;
            }
        });
        totalCostEl.textContent = beautify(totalCost);
    }

    // 施設リストの生成
    BUILDING_META.forEach(b => {
        const obj = (window.Game && Game.ObjectsById) ? Game.ObjectsById[b.id] : null;
        if (!obj) return;

        const currentAmount = obj.amount;

        const row = document.createElement('div');
        row.style.display = 'grid';
        row.style.gridTemplateColumns = 'minmax(80px, 1fr) 135px 45px auto'; // ヘッダーと合わせる
        row.style.alignItems = 'center';
        row.style.gap = '4px';
        row.style.padding = '4px 0';
        row.style.borderBottom = '1px solid rgba(255,255,255,0.05)';

        // --- 1. 施設名 ---
        const nameDiv = document.createElement('div');
        nameDiv.style.display = 'flex';
        nameDiv.style.alignItems = 'center';
        nameDiv.style.gap = '4px';
        nameDiv.style.fontSize = '12px';

        const checkbox = document.createElement('input');
        checkbox.type = 'checkbox';
        checkbox.dataset.id = b.id;
        nameDiv.appendChild(checkbox);
        nameDiv.appendChild(document.createTextNode(b.name));

        // --- 2. 購入数 ---
        const kControlsDiv = document.createElement('div');
        kControlsDiv.style.display = 'flex';
        kControlsDiv.style.alignItems = 'stretch';
        kControlsDiv.style.gap = '1px';
        kControlsDiv.style.width = '100%';
        kControlsDiv.style.boxSizing = 'border-box';

        const kInput = document.createElement('input');
        kInput.type = 'number';
        kInput.value = '0';
        kInput.style.width = '30px';
        kInput.style.textAlign = 'center';
        kInput.style.background = '#111';
        kInput.style.color = '#fff';
        kInput.style.border = '1px solid #555';
        kInput.style.fontSize = '10px';
        kInput.style.padding = '2px 0';
        kInput.style.flex = '1 1 30px';
        kInput.style.boxSizing = 'border-box';

        const kButtons = [-100, -10, -1, 1, 10, 100].map(val => {
            const btn = document.createElement('button');
            btn.textContent = val > 0 ? ('+' + val) : String(val);
            btn.className = 'ccadv_btnsmall';
            btn.style.padding = '2px 0';
            btn.style.fontSize = '9px';
            btn.style.flex = '1 0 16px';
            return { btn, val };
        });

        kControlsDiv.appendChild(kButtons[0].btn); // -100
        kControlsDiv.appendChild(kButtons[1].btn); // -10
        kControlsDiv.appendChild(kButtons[2].btn); // -1
        kControlsDiv.appendChild(kInput);
        kControlsDiv.appendChild(kButtons[3].btn); // +1
        kControlsDiv.appendChild(kButtons[4].btn); // +10
        kControlsDiv.appendChild(kButtons[5].btn); // +100

        // --- 3. 購入後合計 ---
        const totalInput = document.createElement('input');
        totalInput.type = 'number';
        totalInput.value = currentAmount;
        totalInput.style.width = '100%';
        totalInput.style.textAlign = 'center';
        totalInput.style.background = '#111';
        totalInput.style.color = '#fff';
        totalInput.style.border = '1px solid #555';
        totalInput.style.fontSize = '10px';
        totalInput.style.padding = '2px 0';
        totalInput.style.boxSizing = 'border-box';

        // --- 4. コスト ---
        const costDiv = document.createElement('div');
        costDiv.style.textAlign = 'right';
        costDiv.style.fontSize = '10px';
        costDiv.style.wordBreak = 'break-all';

    // --- DOMに追加 ---
        row.appendChild(nameDiv);       // col 1
        row.appendChild(kControlsDiv);  // col 2
        row.appendChild(totalInput);    // col 3
        row.appendChild(costDiv);       // col 4
        listEl.appendChild(row);

        const ui = {
            id: b.id,
            obj: obj,
            checkbox: checkbox,
            kInput: kInput,
            totalInput: totalInput,
            costEl: costDiv
        };
        buildingUIs.push(ui);

        // --- イベントリスナー ---
        const updateFromK = () => {
            let k = parseInt(kInput.value) || 0;
            if (k < 0) { // 購入専用のためマイナスは0にする
                k = 0;
                kInput.value = '0';
            }
            const current = Game.ObjectsById[b.id].amount; // 最新の保有数を取得
            totalInput.value = current + k;
            updateAllCosts();
        };

        const updateFromTotal = () => {
            let total = parseInt(totalInput.value) || 0;
            const current = Game.ObjectsById[b.id].amount;
            if (total < current) { // 現在保有数より少なくはできない
                total = current;
                totalInput.value = total;
            }
            kInput.value = total - current;
            updateAllCosts();
        };

        kInput.addEventListener('input', updateFromK);
        totalInput.addEventListener('input', updateFromTotal);
        checkbox.addEventListener('change', updateAllCosts);

        kButtons.forEach(item => {
            item.btn.addEventListener('click', () => {
                let currentK = parseInt(kInput.value) || 0;
                kInput.value = Math.max(0, currentK + item.val); // 0未満にならないように
                updateFromK();
            });
        });
    });

    // 初期コスト計算
    updateAllCosts();

    // 戻るボタン
    document.getElementById('ccadv_manual_back').addEventListener('click', () => { renderMainView(); });

    // 一括購入ボタン
    buyAllBtn.addEventListener('click', () => {
        buildingUIs.forEach(ui => {
            if (ui.checkbox.checked) {
                const k = parseInt(ui.kInput.value) || 0;
                if (k > 0) {
                    Game.ObjectsById[ui.id].buy(k);
                }
            }
        });

        // 購入後、UIをリフレッシュ
        buildingUIs.forEach(ui => {
            ui.kInput.value = '0';
            ui.totalInput.value = Game.ObjectsById[ui.id].amount;
            ui.checkbox.checked = false;
        });
        updateAllCosts();

        // メインビューのリストも更新されるようにトリガー
        const toplistEl = document.getElementById('ccadv_toplist');
        const buildingListEl = document.getElementById('ccadv_building_list');
        if (toplistEl && buildingListEl) {
            computeAndRenderInto(toplistEl, buildingListEl);
        }
    });
}

// CPS extraction helpers
function parseNumberFromString(s) {
    if (!s) return NaN;
    s = String(s).replace(/,/g, '');
    const m = s.match(/([0-9]+\.?[0-9]*(?:e[+\-]?[0-9]+)?)/i);
    if (m) return parseFloat(m[1]);
    return NaN;
}

function getDisplayedCpsForBuilding(id) {
    try {
        let tooltipText = '';
        if (window.Game && Game.ObjectsById && Game.ObjectsById[id]) {
            const obj = Game.ObjectsById[id];
            if (typeof obj.tooltip === 'function') {
                tooltipText = obj.tooltip();
            }
        }
        if (!tooltipText) {
            const elProd = document.getElementById('product' + id);
            if (elProd) {
                tooltipText = elProd.getAttribute('onmouseover') || elProd.getAttribute('title') || elProd.title || '';
            }
        }
        if (tooltipText) {
            const plainText = tooltipText.replace(/<[^>]*>/g, ' ');
            let match = plainText.match(/毎秒\s*([0-9.,eE+\-]+)/);
            if (match && match[1]) {
                return parseNumberFromString(match[1]);
            }
            match = plainText.match(/([0-9.,eE+\-]+)\s*(cookies per second|per second|\/s|秒あたり)/i);
            if (match && match[1]) {
                return parseNumberFromString(match[1]);
            }
        }
        if (window.Game && Game.CalculateGains) {
            const base = Game.cookiesPs;
            const obj = Game.ObjectsById[id];
            if (!obj) return NaN;
            const orig = obj.amount;
            obj.amount = orig + 1;
            Game.CalculateGains();
            const after = Game.cookiesPs;
            obj.amount = orig;
            Game.CalculateGains();
            const delta = after - base;
            if (isFinite(delta) && delta > 0) return delta;
        }
    } catch (e) { console.error('getDisplayedCpsForBuilding error for id', id, e); }
    const obj = Game.ObjectsById[id];
    if (obj && obj.storedTotalCps && Game.cookiesPs > 0) {
        return obj.storedTotalCps / obj.amount;
    }
    return NaN;
}

// 単位リスト (1e6, 1e9, 1e12, ...)
const NUMBER_UNITS = [
    'million', 'billion', 'trillion', 'quadrillion', 'quintillion',
    'sextillion', 'septillion', 'octillion', 'nonillion', 'decillion',
    'undecillion', 'duodecillion', 'tredecillion', 'quattuordecillion',
    'quindecillion', 'sexdecillion', 'septendecillion', 'octodecillion',
    'novemdecillion', 'vigintillion'
];

function beautify(n) {
    if (!isFinite(n) || n === null || n === undefined) return String(n);

    // 1 million (1e6) 未満
    if (Math.abs(n) < 1e6) {
        // 1e6未満は小数点以下3桁で表示
        return n.toFixed(3);
    }

    // n (1e6) を基準 (index 0) として、指数を計算
    // 1e6 (million) の指数は 6
    const exponent = Math.floor(Math.log10(Math.abs(n)));

    // 単位のインデックスを計算
    // 例: 1e6 (exp 6) -> unitIndex = floor(6/3) - 2 = 2 - 2 = 0 (million)
    // 例: 1e8 (exp 8) -> unitIndex = floor(8/3) - 2 = 2 - 2 = 0 (million)
    // 例: 1e9 (exp 9) -> unitIndex = floor(9/3) - 2 = 3 - 2 = 1 (billion)
    const unitIndex = Math.floor(exponent / 3) - 2;

    if (unitIndex < 0) { // 1e6 未満 (このパスには来ないはずだが念のため)
         return n.toFixed(3);
    }

    if (unitIndex >= NUMBER_UNITS.length) {
        // vigintillion (1e63) を超える場合
        // (1e66 -> exp 66 -> index 20)
        return n.toExponential(3); // フォールバックとして e+ 表記
    }

    // 該当する単位で割る
    // 例: unitIndex 0 (million) -> 10^((0+2)*3) = 1e6
    const divisor = Math.pow(10, (unitIndex + 2) * 3);
    const dividedValue = n / divisor;

    return dividedValue.toFixed(3) + ' ' + NUMBER_UNITS[unitIndex];
}


// --- main loop: 毎秒計算して表示 & 自動購入など ---
let autoClickInterval = null;
if (state.autoClick) performAutoClick(true);
if (state.autoGolden) performAutoGolden(true);
if (state.autoReindeer) performAutoReindeer(true); // ★新機能★

function performAutoClick(enable) {
    if (autoClickInterval) { clearInterval(autoClickInterval);
        autoClickInterval = null; }
    if (enable) {
        autoClickInterval = setInterval(() => { try { if (window.Game && Game.ClickCookie) Game.ClickCookie(); } catch (e) {} }, 50);
    }
}

function performAutoGolden(enable) {
    if (enable) {
        if (!window.__ccadv_golden_interval) {
            window.__ccadv_golden_interval = setInterval(() => {
                try {
                    if (!window.Game || !Game.shimmers) return;
                    for (let i in Game.shimmers) { const s = Game.shimmers[i]; if (s && s.type === 'golden') { try { s.pop(); } catch (e) {} } }
                } catch (e) {}
            }, 100);
        }
    } else {
        if (window.__ccadv_golden_interval) { clearInterval(window.__ccadv_golden_interval);
            window.__ccadv_golden_interval = null; }
    }
}

// ▼▼▼ ★新機能★ ▼▼▼
function performAutoReindeer(enable) {
    if (enable) {
        if (!window.__ccadv_reindeer_interval) {
            // 0.5秒間隔 (500ms)
            window.__ccadv_reindeer_interval = setInterval(() => {
                try {
                    if (!window.Game || !Game.shimmers) return;
                    for (let i in Game.shimmers) {
                        const s = Game.shimmers[i];
                        if (s && s.type === 'reindeer') {
                            try { s.pop(); } catch (e) {}
                        }
                    }
                } catch (e) {}
            }, 500);
        }
    } else {
        if (window.__ccadv_reindeer_interval) { clearInterval(window.__ccadv_reindeer_interval);
            window.__ccadv_reindeer_interval = null; }
    }
}
// ▲▲▲ ★新機能★ ▲▲▲


function computeAndRenderInto(toplistEl, buildingListEl) {
    try {
        if (typeof Game === 'undefined' || !Game.ObjectsById) return;
        // collect owned buildings
        let owned = Game.ObjectsById.filter(o => o && o.amount > 0).map(o => ({ id: o.id, obj: o }));
        if (owned.length === 0) { toplistEl.innerHTML = '<div>まだ購入済みの施設がありません。</div>'; return; }

        // sort by price descending and take top N by price among owned
        owned.sort((a, b) => (b.obj.price || 0) - (a.obj.price || 0));
        let candidates = owned.slice(0, Math.max(state.n, owned.length));

        const list = [];
        for (const c of candidates) {
            const id = c.id;
            if (state.excluded[id]) continue; // exclude
            const obj = c.obj;
            const price = obj.price;
            const displayedCps = getDisplayedCpsForBuilding(id);
            if (!isFinite(displayedCps) || displayedCps <= 0) continue;
            const score = price > 0 ? displayedCps / price : Infinity;
            list.push({ id, name: BUILDING_META[id] ? BUILDING_META[id].name : obj.name, price, cps: displayedCps, score, amount: obj.amount });
        }
        list.sort((a, b) => b.score - a.score);

        // render toplist
        let html = '<div style="font-weight:700;margin-bottom:6px;">上位 ' + Math.min(state.n, list.length) + ' 件（自動購入は有効な建物のみ対象）</div>';
        html += '<ol style="margin:6px 0 0 18px;padding:0;">';
        for (let i = 0; i < Math.min(state.n, list.length); i++) {
            const r = list[i];
            // (コスパの e+ 表示は、非常に小さい数値になるため仕様通りとして残します)
            html += `<li style="margin-bottom:6px;display:flex;align-items:center;gap:8px"><div style="flex:1"><b>${r.name}</b><div class="small">価格:${beautify(r.price)} / CPS:${beautify(r.cps)} / コスパ:${r.score.toExponential(3)} (所持:${r.amount})</div></div></li>`;
        }
        html += '</ol>';
        toplistEl.innerHTML = html;

        // render building list (owned)
        buildingListEl.innerHTML = '';
        for (const o of Game.ObjectsById) {
            if (!o) continue;
            if (o.amount <= 0) continue;
            const bmeta = BUILDING_META[o.id] || { name: o.name };
            const row = document.createElement('div');
            row.className = 'ccadv_building_item';
            const name = document.createElement('div');
            name.style.flex = '1';
            name.innerHTML = `<b>${bmeta.name}</b> <div class='small'>所持:${o.amount} 価格:${beautify(o.price)}</div>`;
            const cb = document.createElement('input');
            cb.type = 'checkbox';
            cb.checked = !!state.excluded[o.id];
            cb.title = 'チェックするとフィルター（除外）されます';
            cb.addEventListener('change', () => { state.excluded[o.id] = cb.checked;
                saveSettings(state);
                computeAndRenderInto(toplistEl, buildingListEl); });
            row.appendChild(cb);
            row.appendChild(name);
            buildingListEl.appendChild(row);
        }

        // auto-purchase: buy top of list if affordable
        if (state.autoPurchase && list.length > 0) {
            const top = list[0];
            if (Game.cookies >= top.price) {
                try {
                    Game.ObjectsById[top.id].buy(1);
                    saveSettings(state);
                    // recompute now synchronously
                    computeAndRenderInto(toplistEl, buildingListEl);
                    return;
                } catch (e) { console.error('auto buy failed', e); }
            }
        }

    } catch (e) { console.error('computeAndRenderInto', e); }
}

// start main loop
let mainLoopInterval = null;

function startMainLoop() {
    if (mainLoopInterval) clearInterval(mainLoopInterval);
    mainLoopInterval = setInterval(() => {
        const toplistEl = document.getElementById('ccadv_toplist');
        const buildingListEl = document.getElementById('ccadv_building_list');
        if (toplistEl && panel.style.display === 'block') {
             computeAndRenderInto(toplistEl, buildingListEl);
        }

        // ▼▼▼ NEW ▼▼▼
        // MP表示更新（毎秒）
        updateMpUI();
        // ▲▲▲ NEW ▲▲▲

    }, 1000);
}
startMainLoop();

// ▼▼▼ NEW ▼▼▼
// 追加: Frenzy(7x) + 施設ブースト同時発生チェック（高頻度）
let detectInterval = null;
function startDetectLoop() {
    if (detectInterval) clearInterval(detectInterval);
    // 250msごとにバフ状態をチェック
    detectInterval = setInterval(() => {
        checkFrenzyBuildingCombo();
        // パネル表示中のみUI反映
        if (panel.style.display === 'block') {
            updateDetectUI();
        }
    }, 250);
}
startDetectLoop();
// ▲▲▲ NEW ▲▲▲


// react to localStorage changes
window.addEventListener('storage', (ev) => {
    if (ev.key === LS_KEY) {
        const s = loadSettings();
        if (s) {
            Object.assign(state, s);
            startMainLoop();
            performAutoClick(state.autoClick);
            performAutoGolden(state.autoGolden);
            performAutoReindeer(state.autoReindeer); // ★新機能★
        }
    }
});

// periodic save
setInterval(() => saveSettings(state), 5000);

// initial render
renderMainView();
})();
